name: Deploy Frontend to Vercel
on:
workflow_dispatch:
jobs:
deploy-frontend:
runs-on: ubuntu-latest
steps:
name: Checkout
uses: actions/checkout@v4
name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 20
name: Install Vercel CLI
run: npm i -g vercel@latest
name: Pull Vercel project settings
working-directory: apps/frontend
env:
VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
run: vercel pull --yes --environment=production --token "$VERCEL_TOKEN"
name: Install deps
working-directory: apps/frontend
run: npm ci || npm install
name: Build (prebuilt)
working-directory: apps/frontend
env:
VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
run: vercel build --prod --token "$VERCEL_TOKEN"
name: Deploy prebuilt to Vercel
working-directory: apps/frontend
env:
VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
run: vercel deploy --prebuilt --prod --token "$VERCEL_TOKEN"
