name: Deploy Frontend to Vercel
on:
workflow_dispatch:
jobs:
deploy-frontend:
runs-on: ubuntu-latest
steps:
name: Checkout
uses: actions/checkout@v4
name: Setup Node
uses: actions/setup-node@v4
with:
node-version: 20
name: Install Vercel CLI
run: npm i -g vercel@latest
name: Link Vercel project (write .vercel/project.json)
working-directory: apps/frontend
run: |
mkdir -p .vercel
cat > .vercel/project.json <<JSON
{"projectId":"${{ secrets.VERCEL_PROJECT_ID }}","orgId":"${{ secrets.VERCEL_ORG_ID }}"}
JSON
name: Deploy (remote build on Vercel)
working-directory: apps/frontend
env:
VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
run: vercel --prod --yes --token "$VERCEL_TOKEN"
